# run test with python3 -m doctest -v ./tests/0-add_integer.txt

>>> add_integer =  __import__('0-add_integer').add_integer

VALID INPUTS:

>>> add_integer(5, 3)
8

>>> add_integer(2.5, 4.2)
6

>>> add_integer(2, 3.5)
5

>>> add_integer(2.5, 3)
5

>>> add_integer(100)
198

TYPE ERRORS:

>>> add_integer("5", 3)
Traceback (most recent call last):
	...
TypeError: a must be an integer

>>> add_integer(5, "3")
Traceback (most recent call last):
	...
TypeError: b must be an integer

>>> add_integer(2.5, "3.5")
Traceback (most recent call last):
    ...
TypeError: b must be an integer

TypeError: a must be an integer

>>> print(add_integer(0, [1, 2, 3]))
Traceback (most recent call last):
	...
TypeError: b must be an integer

FAIL CASES

No args provided

>>> print(add_integer(None))
Traceback (most recent call last):
	...
TypeError: a must be an integer

>>> print(add_integer(None, None))
Traceback (most recent call last):
	...
TypeError: a must be an integer

Extra args

>>> print(add_integer(1, 2, 3))
Traceback (most recent call last):
	...
TypeError: add_integer() takes from 1 to 2 positional arguments but 3 were given

>>> print(add_integer(float("NaN")))
Traceback (most recent call last):
...
ValueError: cannot convert float NaN to integer
